### ISSUE TITLE
`withEntitiesRemoteScrollPagination` doesn't clear cache correctly

### ISSUE THREAD

**Issue by Toeler** [gabrielguerrero/ngrx-traits#128]
The [`clearEntitiesCache`](https://github.com/gabrielguerrero/ngrx-traits/blob/0572475ad966b1a12d420dd1e752eb61c5ebef4d/libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-scroll-pagination.ts#L441) function in `withEntitiesRemoteScrollPagination` only resets `total` and `hasMore`.
Whereas the [`clearEntitiesCache`](https://github.com/gabrielguerrero/ngrx-traits/blob/0572475ad966b1a12d420dd1e752eb61c5ebef4d/libs/ngrx-traits/signals/src/lib/with-entities-pagination/with-entities-remote-pagination.ts#L423) function in `withEntitiesRemotePagination` resets all of the pagination including the `currentPage` and `requestPage`.

As a result, when the filter or remote sort changes and the entities are removed, the pagination has the incorrect state.

**Comment by gabrielguerrero** [comment]
will sort this soon

**Comment by gabrielguerrero** [comment]
@Toeler you can use 17.9.1 it has the fixes you need

**Comment by Toeler** [comment]
Thanks, you didn't have to but it is most appreciated!
