### ISSUE TITLE
Custom local sort

### ISSUE THREAD

**Issue by evgenii-amber** [gabrielguerrero/ngrx-traits#131]
Please add the ability to compare Date object in [local sort](https://github.com/gabrielguerrero/ngrx-traits/blob/main/libs/ngrx-traits/signals/src/lib/with-entities-sort/with-entities-local-sort.util.ts) or even better, add the ability to define custom sort function for specific field.

**Comment by gabrielguerrero** [comment]
@evgenii-amber thanks I think is a nice feature will work on it

**Comment by gabrielguerrero** [comment]
Hey @evgenii-amber , checking the code sorting already supports sorting using Date props, I did not have unit test for it which Im adding now, but did you had any problem sorting with a Date prop?, I will still leave this to add a custom sort function
