### ISSUE TITLE
Question concerning withCustomFeature

### ISSUE THREAD

**Issue by corentinclichy** [gabrielguerrero/ngrx-traits#133]
Hello,

I am trying to play with the withFeatureFactory.

I do undestand the factory with the example but I can passe only part of the store. 

I want to pass the all store. so that I can use 

`patchState(store, setEntity({...project}, { collection: 'projects' }`

But with the example its seems that I can only passe state property from the initial store that will implement the custom features.

Did I miss something ? 

Thanks for your help !

Cheers,
Corentin

**Comment by gabrielguerrero** [comment]
Hey @corentinclichy , you should be able to the everything that is before your custom store, so state , methods and computed and you should be able to call also patch state, maybe if you paste here your case or a stack blitz I can help you better

**Comment by corentinclichy** [comment]
I close this ticket as I get answered from on the discord channel (thanks @francobasilico)
