### ISSUE TITLE
tidy packages

### ISSUE THREAD

**Issue by gremlin896** [gabrielguerrero/ngrx-traits#4]
Align version numbers and clear out any packages not needed

**Comment by gremlin896** [comment]
@angular/cdk - shouldn't be needed

**Comment by gabrielguerrero** [comment]
Ngrx-traits no longer depends on Cdk this was fixed a few days ago, the root package.json does because is use in the examples

**Comment by gabrielguerrero** [comment]
Please reopen if you stilll have more concerns on this
